### PR TITLE
Doc updates

### PR DESCRIPTION
**Pull request by Rubber-Duck-999**
I have made this to help with structure for more things to add and also so we can add Docker later on.

Subfolder for each section, I can add changes to backend and DB separate to your web-app

Can you review this and if so merge?

### CODE REVIEW

**Comment by pororo0721** [comment]
First of all, thanks again for your help.
I read the structure you created carefully. However, I did not think about
the back end at all because I conceived a static web as the first plan.
I've also learned about react, but I'm still not very good at it and I
don't know anything about redux.
So I am a little confused as to how to change and proceed with this project.

2022년 3월 15일 (화) 오후 1:00, Rubberduck ***@***.***>님이 작성:

**Comment by Rubber-Duck-999** [comment]
@pororo0721 will you only be developing a web application then? I would suggest adding this in to help the structure if you ever do want to change it

**Comment by Rubber-Duck-999** [comment]
I would suggest either use this project as learning or move forward by starting a new project later for more elements because you will need to if you want to store state for users

**Comment by pororo0721** [comment]
Sorry for the late reply.
I thought about it yesterday, and I want to proceed with this project
according to my original plan.
First of all, I know you want me to learn more through this project, but
when I first planned this project, my goal was to become more familiar with
React.
Of course, I have used nodeJs and express, but I am not proficient and I
have never learned redux at all. So, when I saw the plan you sent me
yesterday, I was very worried.
So, as originally planned and decided, I want to focus more on using React
for this project. I am very grateful for giving me such a wonderful
opportunity, but I am sorry that I turned it down.



2022년 3월 15일 (화) 오후 4:15, Rubberduck ***@***.***>님이 작성:
I would suggest either use this project as learning or move forward by
starting a new project later for more elements because you will need to if
you want to store state for users

**Comment by Rubber-Duck-999** [comment]
So would you like support for react?

**Comment by pororo0721** [comment]
I'll ask you if there's any blockage while I'm on my own.
Thank you for taking the time to help.

2022년 3월 16일 (수) 오후 12:10, Rubberduck ***@***.***>님이 작성:

**Comment by Rubber-Duck-999** [comment]
Okay I will leave you be, I will close the PR

**Pull request closed without merging**
